image:
  repository: weezyval/go-httpbin:aa254d5
  pullPolicy: Always

replicaCount: 1
namespace: go-httpbin
containerPort: 8080

service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 100Mi

