name: Lint

on:
  push:
    branches: [dev, main] # pushes TO dev
  pull_request:
    branches: [dev, main] # pull requests AGAINST dev

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39.0